-- =============================================================================
-- ScopeGuard — Initial schema
-- =============================================================================
-- Generated by `prisma migrate dev --name init` against the schema in
-- prisma/schema.prisma. Hand-edited only to add table/column COMMENT ON
-- statements that drive `docs/schema.md`. Do not regenerate without merging
-- those comments back in.
-- =============================================================================

-- ---------- Enums ----------------------------------------------------------

CREATE TYPE "PlanTier"          AS ENUM ('FREE', 'STARTER', 'PRO', 'BUSINESS');
CREATE TYPE "ProjectStatus"     AS ENUM ('ACTIVE', 'COMPLETED', 'ARCHIVED');
CREATE TYPE "ScopeVerdict"      AS ENUM ('IN_SCOPE', 'OUT_OF_SCOPE', 'AMBIGUOUS');
CREATE TYPE "UserAction"        AS ENUM ('SENT_CHANGE_ORDER', 'IGNORED', 'ACCEPTED_ANYWAY');
CREATE TYPE "TransactionType"   AS ENUM ('INCOME', 'EXPENSE');
CREATE TYPE "IntegrationSource" AS ENUM ('STRIPE', 'PAYPAL', 'GUMROAD', 'SHOPIFY', 'ETSY', 'UPWORK', 'WISE', 'PLAID');
CREATE TYPE "Jurisdiction"      AS ENUM ('US', 'CA', 'UK');

-- ---------- users ----------------------------------------------------------

CREATE TABLE "users" (
  "id"                UUID NOT NULL DEFAULT gen_random_uuid(),
  "email"             TEXT NOT NULL,
  "stripeCustomerId"  TEXT,
  "planTier"          "PlanTier" NOT NULL DEFAULT 'FREE',
  "inboundEmailAlias" TEXT NOT NULL,
  "timezone"          TEXT NOT NULL DEFAULT 'America/Toronto',
  "jurisdiction"      "Jurisdiction" NOT NULL DEFAULT 'US',
  "createdAt"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"         TIMESTAMP(3) NOT NULL,
  CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "users_stripeCustomerId_key" ON "users"("stripeCustomerId");
CREATE UNIQUE INDEX "users_inboundEmailAlias_key" ON "users"("inboundEmailAlias");
CREATE INDEX "users_planTier_idx" ON "users"("planTier");

COMMENT ON TABLE  "users" IS 'ScopeGuard customer. Row id mirrors auth.users.id.';
COMMENT ON COLUMN "users"."inboundEmailAlias" IS 'Per-user forwarding alias users send client emails to.';
COMMENT ON COLUMN "users"."planTier" IS 'Active subscription tier — set by Stripe webhook.';

-- ---------- projects -------------------------------------------------------

CREATE TABLE "projects" (
  "id"          UUID NOT NULL DEFAULT gen_random_uuid(),
  "userId"      UUID NOT NULL,
  "name"        TEXT NOT NULL,
  "clientName"  TEXT NOT NULL,
  "clientEmail" TEXT,
  "status"      "ProjectStatus" NOT NULL DEFAULT 'ACTIVE',
  "hourlyRate"  DECIMAL(10,2),
  "currency"    TEXT NOT NULL DEFAULT 'USD',
  "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP(3) NOT NULL,
  CONSTRAINT "projects_pkey"        PRIMARY KEY ("id"),
  CONSTRAINT "projects_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE INDEX "projects_userId_status_idx"      ON "projects"("userId", "status");
CREATE INDEX "projects_userId_clientEmail_idx" ON "projects"("userId", "clientEmail");

COMMENT ON TABLE  "projects" IS 'Freelance engagement; owns Contracts and ScopeChecks.';

-- ---------- contracts ------------------------------------------------------

CREATE TABLE "contracts" (
  "id"               UUID NOT NULL DEFAULT gen_random_uuid(),
  "projectId"        UUID NOT NULL,
  "fileName"         TEXT NOT NULL,
  "storageKey"       TEXT NOT NULL,
  "rawText"          TEXT,
  "parsedAt"         TIMESTAMP(3),
  "deliverables"     JSONB,
  "exclusions"       JSONB,
  "ambiguousTerms"   JSONB,
  "paymentTerms"     JSONB,
  "overallRiskScore" INTEGER,
  "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "contracts_pkey"           PRIMARY KEY ("id"),
  CONSTRAINT "contracts_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE
);

CREATE INDEX "contracts_projectId_parsedAt_idx" ON "contracts"("projectId", "parsedAt");

COMMENT ON TABLE  "contracts" IS 'Uploaded contract document plus its AI-extracted structure.';
COMMENT ON COLUMN "contracts"."storageKey"       IS 'Object key in Supabase Storage `contracts` bucket.';
COMMENT ON COLUMN "contracts"."deliverables"     IS 'JSON array — see lib/ai/parseContract.ts ParsedContract.deliverables.';
COMMENT ON COLUMN "contracts"."ambiguousTerms"   IS 'JSON array of vague phrases flagged for the user.';

-- ---------- scope_checks ---------------------------------------------------

CREATE TABLE "scope_checks" (
  "id"                UUID NOT NULL DEFAULT gen_random_uuid(),
  "projectId"         UUID NOT NULL,
  "contractId"        UUID,
  "rawEmailContent"   TEXT NOT NULL,
  "emailSubject"      TEXT,
  "emailFromAddress"  TEXT,
  "verdict"           "ScopeVerdict" NOT NULL,
  "confidence"        DOUBLE PRECISION NOT NULL,
  "citedClause"       TEXT,
  "clauseReference"   TEXT,
  "draftResponse"     TEXT,
  "changeOrderText"   TEXT,
  "estimatedHours"    DOUBLE PRECISION,
  "userAction"        "UserAction",
  "createdAt"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "scope_checks_pkey"           PRIMARY KEY ("id"),
  CONSTRAINT "scope_checks_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE
);

CREATE INDEX "scope_checks_projectId_createdAt_idx" ON "scope_checks"("projectId", "createdAt" DESC);
CREATE INDEX "scope_checks_verdict_idx"             ON "scope_checks"("verdict");

COMMENT ON TABLE  "scope_checks" IS 'One inbound message + verdict. Immutable once written.';

-- ---------- transactions ---------------------------------------------------

CREATE TABLE "transactions" (
  "id"             UUID NOT NULL DEFAULT gen_random_uuid(),
  "userId"         UUID NOT NULL,
  "source"         "IntegrationSource" NOT NULL,
  "externalId"     TEXT NOT NULL,
  "type"           "TransactionType" NOT NULL,
  "amount"         DECIMAL(12,2) NOT NULL,
  "currency"       TEXT NOT NULL,
  "description"    TEXT,
  "category"       TEXT,
  "taxDeductible"  BOOLEAN NOT NULL DEFAULT false,
  "receiptKey"     TEXT,
  "occurredAt"     TIMESTAMP(3) NOT NULL,
  "createdAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "transactions_pkey"        PRIMARY KEY ("id"),
  CONSTRAINT "transactions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "transactions_source_externalId_key"   ON "transactions"("source", "externalId");
CREATE INDEX        "transactions_userId_occurredAt_idx"   ON "transactions"("userId", "occurredAt" DESC);
CREATE INDEX        "transactions_userId_type_occurredAt_idx" ON "transactions"("userId", "type", "occurredAt");

COMMENT ON TABLE "transactions" IS 'Unified financial transaction record from any IntegrationSource.';

-- ---------- integrations ---------------------------------------------------

CREATE TABLE "integrations" (
  "id"             UUID NOT NULL DEFAULT gen_random_uuid(),
  "userId"         UUID NOT NULL,
  "source"         "IntegrationSource" NOT NULL,
  "accessToken"    TEXT NOT NULL,
  "refreshToken"   TEXT,
  "tokenExpiresAt" TIMESTAMP(3),
  "lastSyncedAt"   TIMESTAMP(3),
  "isActive"       BOOLEAN NOT NULL DEFAULT true,
  "metadata"       JSONB,
  "createdAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "integrations_pkey"        PRIMARY KEY ("id"),
  CONSTRAINT "integrations_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "integrations_userId_source_key"   ON "integrations"("userId", "source");
CREATE INDEX        "integrations_userId_isActive_idx" ON "integrations"("userId", "isActive");

COMMENT ON TABLE  "integrations" IS 'OAuth/API credentials linking a user to a third-party platform.';
COMMENT ON COLUMN "integrations"."accessToken"  IS 'AES-256-GCM ciphertext (iv:tag:cipher hex triples). NEVER log.';
COMMENT ON COLUMN "integrations"."refreshToken" IS 'AES-256-GCM ciphertext. NEVER log.';
